version: 2
updates:
  - package-ecosystem: "github-actions" 
    directory: "/" 
    schedule:
      interval: "daily"
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: daily
      time: "13:00"
    groups:
      python-packages:
        patterns:
          - "*"