version: '3.8'

services:
  spotlight-storage:
    build:
      context: .
    environment:
      - TRANSLATIONS_DIR=/app/static/translations
    image: spotlight_storage_v4
    ports:
      - "5000:5000"
      - "5001:5001"
    restart: always
    volumes:
      - ./data:/data:rw
      - ./images:/images:rw
      - ./static/translations:/app/static/translations:ro
    command: >
      bash -c "python setup.py && python app.py"
