blank_issues_enabled: false
contact_links:
  - name: Feature Request
    url: https://github.com/devzwf/Spotlight_Storage/discussions/new?category=feature-request
    about: Please use this form to request a new feature or enhancement for Spotlight_Storage.